#! /bin/bash

KERNEL="zImage"
DT="at91sam9g35ek.dtb"
SSH_TARGET="engr$.admin@chlorine"

cd $BUILDROOT
rm -rf output/build/linux-4.4-at91
rm dl/linux-4.4-at91.tar.gz
./generate-flash-images.sh
scp output/images/$KERNEL $SSH_TARGET:/tmp
scp output/images/$DT $SSH_TARGET:/tmp
ssh -x -C $SSH_TARGET flash_unlock /dev/mtd5 0 900
ssh -x -C $SSH_TARGET flashcp -v /tmp/$KERNEL /dev/mtd4
ssh -x -C $SSH_TARGET flashcp -v /tmp/$DT /dev/mtd3
/opt/Projects/cm130/source/scripts/rebootTarget.sh
